#!/bin/bash
source .extra/namegen
declare -- list
declare -- temp
for item in $1; do
	if [[ -z "$list" ]]; then
		compound_call list "$item" genname genwild genshname
	else
		compound_call temp "$item" genname genwild genshname
		list+=" $temp"
	fi
done
echo "$list"
