#!/bin/bash
set -e

if [[ -f "$installdir"/lib64/libcustomutils.a ]] || [[ -f "$installdir"/lib64/libcustomutils.so ]]; then
	rm -f "$installdir"/lib64/libcustomutils.a "$installdir"/lib64/libcustomutils.so
	echo "removing test objects, as they might be linked with -lcustomutils" >&2
	rm -f *.o
fi

cd libs && make uninstall
