#!/bin/bash
set -e

if [[ -d "${installabs}/include/CPPExtensions" ]]; then
	(cd headers && .extra/rmdep)
fi

echo "making include directory" >&2
mkdir -p -v "${installabs}/include/CPPExtensions/.part"
echo "installing header files" >&2
cp -u -t "${installabs}/include/CPPExtensions" headers/*.hpp
cp -u -t "${installabs}/include/CPPExtensions/.part" headers/.part/*.hpp
