#!/bin/bash
set -e

if [[ -d "${installabs}/include/CustomUtils" ]]; then
	echo "removing previous header installation" >&2
	rm -r "${installabs}/include/CustomUtils"
fi

echo "making include directory" >&2
mkdir -p -v "${installabs}/include/CustomUtils"
echo "installing header files" >&2
cp -u -t "${installabs}/include/CustomUtils" headers/*.hpp
