#!/bin/bash
set -e
shopt -s dotglob nullglob

if [[ -d "${installabs}/include/CPPExtensions" ]]; then
	declare -a headers=("${installabs}"/include/CPPExtensions/*)
	if ((${#headers[@]})); then
		echo "removing headers"
		rm -r "${headers[@]}"
	fi
	rmdir -v "${installabs}/include/CPPExtensions"
fi
