#!/bin/bash
set -e

if [[ -e "/usr/local/include/CustomUtils" ]]; then
	if [[ -L "headers" ]]; then
		echo "unlinking headers" >&2
		unlink headers
	else
		echo "removing headers" >&2
		rm -r headers
	fi
	echo "moving headers back to source directory" >&2
	mv /usr/local/include/CustomUtils headers
fi
